"""empty message

Revision ID: 48dd34c05f28
Revises: bc0dd0f8a01a
Create Date: 2020-04-08 14:10:16.485834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dd34c05f28'
down_revision = 'bc0dd0f8a01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'location')
    # ### end Alembic commands ###
