"""empty message

Revision ID: 815c09d14e60
Revises: 65629ee64dd8
Create Date: 2020-03-14 10:40:46.604969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815c09d14e60'
down_revision = '65629ee64dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('Biography', sa.String(length=150), nullable=True))
    op.add_column('user_profiles', sa.Column('firstname', sa.String(length=80), nullable=False))
    op.add_column('user_profiles', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.add_column('user_profiles', sa.Column('profilepicture', sa.String(length=255), nullable=True))
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'profilephoto')
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('bio', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('profilephoto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'profilepicture')
    op.drop_column('user_profiles', 'lastname')
    op.drop_column('user_profiles', 'firstname')
    op.drop_column('user_profiles', 'Biography')
    # ### end Alembic commands ###
