"""empty message

Revision ID: c2746fc61a0a
Revises: 815c09d14e60
Create Date: 2020-03-14 10:41:11.939873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2746fc61a0a'
down_revision = '815c09d14e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=150), nullable=True))
    op.drop_column('user_profiles', 'Biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('Biography', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
